#! /bin/sh

sxhkd &
picom &
# /home/rallen/.config/polybar/launch.sh &
polybar.sh &
# xrandr --output DisplayPort-1 --primary --mode 1920x1080 --rate 143.85 &
# xrandr --output DVI-D-0 --mode 1920x1080 --rate 119.98 --rotate left &
# feh --bg-cente ~/Pictures/wallpaper/quake_desktop.png &
monitors.sh &

bspc monitor DisplayPort-1 -n 0 -d 1 2 3 4 5  
bspc monitor DVI-D-0 -n 1 -d 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^1'
bspc rule -a Chromium desktop='^1'
bspc rule -a discord desktop='^6'
bspc rule -a Steam desktop='^3'
bspc rule -a obs desktop='^8'
bspc rule -a tc-twitch desktop='^6'
bspc rule -a pavucontrol state=floating
bspc rule -a ezquake.bin desktop='^2' state=fullscreen follow=on
bspc rule -a epicgameslauncher.exe desktop='^5' state=floating
bspc rule -a Lutris desktop='^4' state=floating

# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
