#!/bin/sh

bspc monitor DP-2 -d 1 2 3  
bspc monitor DP-0 -d 4 5 6 7

background=$(xrdb -query | grep "background" | cut -f2 | sed -r 's/#//' | head -n 1)
foreground=$(xrdb -query | grep "foreground" | cut -f2 | sed -r 's/#//' | head -n 1)
color0=$(xrdb -query | grep "color0" | cut -f2 | sed -r 's/#//' | head -n 1)
color1=$(xrdb -query | grep "color1" | cut -f2 | sed -r 's/#//' | head -n 1)
color2=$(xrdb -query | grep "color2" | cut -f2 | sed -r 's/#//' | head -n 1)
color3=$(xrdb -query | grep "color3" | cut -f2 | sed -r 's/#//' | head -n 1)
color4=$(xrdb -query | grep "color4" | cut -f2 | sed -r 's/#//' | head -n 1)
color5=$(xrdb -query | grep "color5" | cut -f2 | sed -r 's/#//' | head -n 1)
color6=$(xrdb -query | grep "color6" | cut -f2 | sed -r 's/#//' | head -n 1)
color7=$(xrdb -query | grep "color7" | cut -f2 | sed -r 's/#//' | head -n 1)
color8=$(xrdb -query | grep "color8" | cut -f2 | sed -r 's/#//' | head -n 1)

bspc config border_width        4 
bspc config window_gap          24

bspc config split_ratio          0.62
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#xresources not working now for some reason...
#bspc config normal_border_color "#$color8"
#bspc config active_border_color "#$color9"
#bspc config focused_border_color "#$color9"
#bspc config presel_feedback_color "#$color1"

bspc config normal_border_color "#282828"
bspc config active_border_color "#282828"
bspc config focused_border_color "#fb4934"
bspc config presel_feedback_color "#cc241d"


bspc rule -a ezquake.bin desktop=^5 follow=on
bspc rule -a discord desktop=^1
bspc rule -a Brave-browser desktop=^4
bspc rule -a Steam desktop=^5
bspc rule -a obs desktop=^3
bspc rule -a ezquake-linux-x86_64 desktop=^5 state=fullscreen follow=on
bspc rule -a unezquake-linux-x86_64 desktop=^5 state=fullscreen follow=on

# Autostart
# keep services running
(pgrep picom || picom --experimental-backends ) &
(pgrep sxhkd || sxhkd ) &
(pgrep polybar || polybar.sh ) &
(pgrep dunst || dunst ) &

# main apps
(pgrep brave || brave-browser ) &
(pgrep discord || discord ) &

