#!/bin/bash
# Arch upgradeable packages

# Count them up
list=`pacman -Qu 2> /dev/null`

if [ "$list" == "" ]; then
    count=0
else
    count=`echo "$list" | wc -l`
fi

# Print them out

if [ "$count" == "0" ]; then
	echo ""
else
        echo " $count" # just this line for always
fi

