" Keep defaults with .vimrc
unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

" Sensible defaults
filetype plugin on
filetype indent on
syntax on
colo torte

" turn hybrid line numbers on
:set number relativenumber
:set nu rnu

" vim-plug
call plug#begin()
Plug 'dylanaraps/wal.vim'

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'preservim/nerdtree'

call plug#end()


" Put your non-Plugin stuff after this line
"
hi Normal guibg=NONE ctermbg=NONE
