#!/bin/sh

case $BUTTON in
  1) "$TERMINAL" -e "pulsemixer" ;;
esac

vol="$(pamixer --get-volume)"
sink="$(pamixer --get-default-sink)"

if [ "$sink" = "alsa_output.pci-0000_2d_00.1.hdmi-stereo" ]; then
	out_icon="蓼"
else
	out_icon=""
fi

[ $(pamixer --get-mute) = true ] && echo "$out_icon 🔇" && exit

echo "$out_icon $vol%"
