if [ -n "$DISPLAY" ]; then
    export BROWSER="brave"
else 
    export BROWSER="links"
fi

export VISUAL="nvim"
export EDITOR="nvim"
export TERM="xterm-256color"
export TERMINAL="alacritty"


if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

if [ -d "$HOME/scripts" ] ; then
    PATH="$HOME/scripts:$PATH"
fi

if [ -d "$HOME/scripts/statusbar" ] ; then
    PATH="$HOME/scripts/statusbar:$PATH"
fi

if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
